### ISSUE TITLE
Unable to find images or sprites.

### ISSUE THREAD

**Issue by FabledIndiaGames** [Blobfolio/js-mate-poe#2]
Looking to change edit play with sprite or images but unable to locate them.

**Comment by joshstoik1** [comment]
@FabledIndiaGames The main image sprite is at https://github.com/Blobfolio/js-mate-poe/blob/master/skel/img/poe.png, but some visuals rely on CSS ([here](https://github.com/Blobfolio/js-mate-poe/blob/master/skel/scss/_base.scss) and [here](https://github.com/Blobfolio/js-mate-poe/blob/master/skel/scss/_base.scss)) instead/too.

Those assets are embedded at compile-time, so you'll need to (re)build the library from source to see any changes in action. The `director` feature is useful for testing; it'll dump extra details to the browser's console and expose a `Poe.play` setter method that can be used to trigger arbitrary sequences on demand.
